In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from scipy import stats

Dataset

In [17]:
data = pd.read_csv("snp_data.csv")
data

ID     trait  snp1_A/G  snp2_C/T  snp3_G/T
0    APID0001 -0.909573       1.0       2.0       1.0
1    APID0002 -1.042890       0.0       1.0       2.0
2    APID0003 -0.564743       1.0       1.0       0.0
3    APID0004  0.281898       1.0       0.0       1.0
4    APID0005 -1.119414       0.0       2.0       1.0
..        ...       ...       ...       ...       ...
663  APID0664 -1.395477       2.0       2.0       0.0
664  APID0665  0.484364       0.0       0.0       0.0
665  APID0666  0.273132       1.0       1.0       2.0
666  APID0667 -0.888352       1.0       1.0       0.0
667  APID0668 -0.032362       1.0       1.0       1.0

[668 rows x 5 columns]

In [20]:
data = data.dropna()
data

ID     trait  snp1_A/G  snp2_C/T  snp3_G/T
0    APID0001 -0.909573       1.0       2.0       1.0
1    APID0002 -1.042890       0.0       1.0       2.0
2    APID0003 -0.564743       1.0       1.0       0.0
3    APID0004  0.281898       1.0       0.0       1.0
4    APID0005 -1.119414       0.0       2.0       1.0
..        ...       ...       ...       ...       ...
663  APID0664 -1.395477       2.0       2.0       0.0
664  APID0665  0.484364       0.0       0.0       0.0
665  APID0666  0.273132       1.0       1.0       2.0
666  APID0667 -0.888352       1.0       1.0       0.0
667  APID0668 -0.032362       1.0       1.0       1.0

[658 rows x 5 columns]

In [21]:
Y_snp_1 = np.array(data['snp1_A/G'])
Y_snp_2 = data['snp2_C/T']
Y_snp_3 = data['snp3_G/T']
X = np.array( data['trait'])

Linear regression coefficient (slope) for each snp:

In [42]:
linear_reg_snp_1 = LinearRegression(fit_intercept=True, copy_X=True, n_jobs=None, positive=False).fit(X.reshape(-1, 1), Y_snp_1)
linear_reg_snp_1.coef_

array([-0.01355892])

In [43]:
linear_reg_snp_2 = LinearRegression(fit_intercept=True, copy_X=True, n_jobs=None, positive=False).fit(X.reshape(-1, 1), Y_snp_2)
linear_reg_snp_2.coef_

array([-0.10263911])

In [44]:
linear_reg_snp_3 = LinearRegression(fit_intercept=True, copy_X=True, n_jobs=None, positive=False).fit(X.reshape(-1, 1), Y_snp_3)
linear_reg_snp_3.coef_

array([-0.05175373])

Descriptive statistics for each snp, print the p-value:

In [38]:
 slope_snp_1, intercept_snp_1, r_value_snp_1, p_value_snp_1, std_err_snp_1 = stats.linregress(X, Y_snp_1)
 p_value_snp_1

0.6154774350538481

In [39]:
 slope_snp_2, intercept_snp_2, r_value_snp_2, p_value_snp_2, std_err_snp_2 = stats.linregress(X, Y_snp_2)
 p_value_snp_2

4.886231087468563e-05

In [40]:
 slope_snp_3, intercept_snp_3, r_value_snp_3, p_value_snp_3, std_err_snp_3 = stats.linregress(X, Y_snp_3)
 p_value_snp_3

0.0492249879608227

In [33]:
# Y_snp_2_pred = linear_reg_snp_2.predict(X.reshape(-1, 1))
# plt.scatter(X, Y_snp_2, color="black")
# plt.plot(X, Y_snp_2_pred, color="blue", linewidth=3)

# plt.xticks(())
# plt.yticks(())

# plt.show()

In [ ]:
# Y_snp_3_pred = linear_reg_snp_3.predict(X.reshape(-1, 1))
# plt.scatter(X, Y_snp_3, color="black")
# plt.plot(X, Y_snp_3_pred, color="blue", linewidth=3)

# plt.xticks(())
# plt.yticks(())

# plt.show()

In [ ]:
# Y_snp_1_pred = linear_reg.predict(X.reshape(-1, 1))
# plt.scatter(X, Y_snp_1, color="black")
# plt.plot(X, Y_snp_1_pred, color="blue", linewidth=3)

# plt.xticks(())
# plt.yticks(())

# plt.show()